kbaseURL = "http://example.org/"
languageCode = "en-us"
title = "Harlan Hutton"
theme = "monopriv"

[params]
about = "M.S. in Data Science Student at New York University's Center for Data Science"
github = "https://github.com/harlanhutton"
email = "ahh303@nyu.edu"
linkedin = "https://www.linkedin.com/in/harlan-hutton-49a189150/"
